### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by TraceBox1357** [OmriHayat/sami#1]

**Comment by OmriHayat** [comment]
תודה לך חבר,
בנימה זאת,kys

**Comment by TraceBox1357** [comment]
L+Ratio

**Comment by razflash** [comment]
L +counter ratio

**Comment by TraceBox1357** [comment]
have you heard of joe

**Comment by razflash** [comment]
💀

**Comment by TraceBox1357** [comment]
💀

**Comment by OmriHayat** [comment]
fuck are yall talking bout gay ass niggas ong im finnna shoot up yo class on my granny kids expect me faggots.
and thats on god.

**Comment by razflash** [comment]
https://www.youtube.com/watch?v=AQqDdAY7wy0
